### PR TITLE
Arduino and cmake support

### PR DESCRIPTION
**Pull request by pschatzmann**
I made the following changes:
- support to include as Arduino library
- support to build and download library with cmake
- support for c++

### CODE REVIEW

**Comment by pschatzmann** [comment]
I provide some intregration of your library in my [Arduino AudioTools](https://github.com/pschatzmann/arduino-audio-tools):
- Here is a [test that I built on my desktop](https://github.com/pschatzmann/arduino-audio-tools/blob/main/cmake-tests/codec/adpcm/adpcm.cpp)
- And one for [ESP32 Arduino](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/tests/codecs/test-codec-adpcm/test-codec-adpcm.ino)

**Comment by dbry** [comment]
Hey thanks, this nice! I have never tried out an Arduino, although I have used ESP32's and tons of RPi's.

I tried the cmake file and it doesn't seem to generate an executable (just the library). Is that easy to add? I guess it wouldn't make sense on an Arduino, but certainly on some other platforms.

**Comment by pschatzmann** [comment]
Good point: I extended the cmake to build both, an executable and the library.

On the ESP32 it seems to work only with LOOKAHEAD 0 and NOISE_SHAPING_OFF

**Comment by dbry** [comment]
> Good point: I extended the cmake to build both, an executable and the library.

Great!

> On the ESP32 it seems to work only with LOOKAHEAD 0 and NOISE_SHAPING_OFF

I don't explicitly mention this, but the _encoder_ is really not intended as an embedded target. It achieves the quality through a lot of complex and costly stuff, including possibly deep recursion. The idea is that the encoding would be done offline to generate canned audio. The _decoder_, on the other hand, is very embedded-friendly. I'm not why the noise shaping would not work as that's pretty simple.

That said, if the encoder is used without lookahead, then it should be fine.

**Pull request merged**
